name: ilve
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.9.0
  - torchvision
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - pillow
  - scipy
  - scikit-learn
  - pip
  - pip:
    - streamlit>=1.28.0
    - plotly>=5.0.0
    - pyyaml>=6.0
    - pandas>=1.3.0
    - seaborn>=0.11.0
    - tqdm>=4.60.0
    - wandb  
    - pytest>=7.0.0  
    - black>=22.0.0  
    - flake8>=4.0.0  