[theme]
# Utiliser le thème par défaut (clair)
base = "light"

# Ou pour forcer les couleurs :
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[global]
developmentMode = false